/* IEOP · Obras — dados mock realistas (Município de Macaé)
   Espelha ObraListItem (obras.schema.ts). ieop_classe/risco derivados. */

window.OBRAS = [
  { id: "1",  nome: "Reforma da UBS do Parque Aeroporto",          numero_contrato: "CT-2024-0182", secretaria: "Sec. Mun. de Saúde",          bairro: "Parque Aeroporto",       status: "atrasada",     execucao_percentual: 34, valor_contratado: 4_820_000,  prob_atraso: 0.88, ieop_score: 38.4, previsao_termino: "2026-03-15" },
  { id: "2",  nome: "Pavimentação da Estrada de Cabiúnas",         numero_contrato: "CT-2023-0941", secretaria: "Sec. Mun. de Obras",          bairro: "Cabiúnas",               status: "em_andamento", execucao_percentual: 52, valor_contratado: 12_400_000, prob_atraso: 0.81, ieop_score: 44.1, previsao_termino: "2026-07-30" },
  { id: "3",  nome: "Ampliação da Escola Mun. Luiz Reid",          numero_contrato: "CT-2024-0067", secretaria: "Sec. Mun. de Educação",       bairro: "Aroeira",                status: "em_andamento", execucao_percentual: 61, valor_contratado: 6_750_000,  prob_atraso: 0.74, ieop_score: 51.7, previsao_termino: "2026-05-20" },
  { id: "4",  nome: "Drenagem do Bairro Malvinas",                 numero_contrato: "CT-2023-0788", secretaria: "Sec. Mun. de Infraestrutura", bairro: "Malvinas",               status: "paralisada",   execucao_percentual: 28, valor_contratado: 8_900_000,  prob_atraso: 0.69, ieop_score: 41.2, previsao_termino: "2026-09-10" },
  { id: "5",  nome: "Construção da Praça de Imbetiba",             numero_contrato: "CT-2024-0203", secretaria: "Sec. Mun. de Obras",          bairro: "Imbetiba",               status: "em_andamento", execucao_percentual: 45, valor_contratado: 3_200_000,  prob_atraso: 0.63, ieop_score: 56.3, previsao_termino: "2026-04-28" },
  { id: "6",  nome: "Requalificação da Orla de Cavaleiros",        numero_contrato: "CT-2023-0512", secretaria: "Sec. Mun. de Obras",          bairro: "Cavaleiros",             status: "em_andamento", execucao_percentual: 78, valor_contratado: 22_600_000, prob_atraso: 0.31, ieop_score: 72.8, previsao_termino: "2026-02-12" },
  { id: "7",  nome: "Nova Creche Municipal de Lagomar",            numero_contrato: "CT-2024-0119", secretaria: "Sec. Mun. de Educação",       bairro: "Lagomar",                status: "concluida",    execucao_percentual: 100, valor_contratado: 5_400_000, prob_atraso: 0.08, ieop_score: 86.5, previsao_termino: "2025-11-30" },
  { id: "8",  nome: "Hospital de Campanha — Nova Macaé",           numero_contrato: "CT-2022-0339", secretaria: "Sec. Mun. de Saúde",          bairro: "Nova Macaé",             status: "concluida",    execucao_percentual: 100, valor_contratado: 18_700_000, prob_atraso: 0.12, ieop_score: 81.0, previsao_termino: "2025-08-22" },
  { id: "9",  nome: "Ciclovia da Avenida Atlântica",               numero_contrato: "CT-2024-0288", secretaria: "Sec. Mun. de Infraestrutura", bairro: "Riviera Fluminense",     status: "em_andamento", execucao_percentual: 67, valor_contratado: 4_100_000,  prob_atraso: 0.42, ieop_score: 64.9, previsao_termino: "2026-06-05" },
  { id: "10", nome: "Parque Linear do Rio Macaé",                  numero_contrato: "CT-2023-0654", secretaria: "Sec. Mun. de Meio Ambiente",  bairro: "Centro",                 status: "em_andamento", execucao_percentual: 39, valor_contratado: 9_300_000,  prob_atraso: 0.58, ieop_score: 53.4, previsao_termino: "2026-10-18" },
  { id: "11", nome: "Quadra Poliesportiva da Glória",              numero_contrato: "CT-2024-0145", secretaria: "Sec. Mun. de Esportes",       bairro: "Glória",                 status: "concluida",    execucao_percentual: 100, valor_contratado: 2_650_000, prob_atraso: 0.05, ieop_score: 88.2, previsao_termino: "2025-09-14" },
  { id: "12", nome: "Recapeamento da Av. Rui Barbosa",             numero_contrato: "CT-2023-0877", secretaria: "Sec. Mun. de Obras",          bairro: "Centro",                 status: "atrasada",     execucao_percentual: 56, valor_contratado: 7_800_000,  prob_atraso: 0.71, ieop_score: 47.6, previsao_termino: "2026-01-25" },
  { id: "13", nome: "Estação de Tratamento de Esgoto — Barra",     numero_contrato: "CT-2022-0410", secretaria: "Sec. Mun. de Infraestrutura", bairro: "Barra de Macaé",         status: "paralisada",   execucao_percentual: 19, valor_contratado: 31_500_000, prob_atraso: 0.66, ieop_score: 35.9, previsao_termino: "2027-02-28" },
  { id: "14", nome: "Reforma do Mercado Municipal",                numero_contrato: "CT-2024-0231", secretaria: "Sec. Mun. de Obras",          bairro: "Centro",                 status: "nao_iniciada", execucao_percentual: 0,  valor_contratado: 5_900_000,  prob_atraso: 0.35, ieop_score: null, previsao_termino: "2026-11-05" },
  { id: "15", nome: "Posto de Saúde da Granja dos Cavaleiros",     numero_contrato: "CT-2024-0094", secretaria: "Sec. Mun. de Saúde",          bairro: "Granja dos Cavaleiros",  status: "em_andamento", execucao_percentual: 83, valor_contratado: 6_300_000,  prob_atraso: 0.22, ieop_score: 76.1, previsao_termino: "2026-03-30" },
  { id: "16", nome: "Arborização Urbana — Fase 2",                 numero_contrato: "CT-2023-0723", secretaria: "Sec. Mun. de Meio Ambiente",  bairro: "Cavaleiros",             status: "concluida",    execucao_percentual: 100, valor_contratado: 1_450_000, prob_atraso: 0.10, ieop_score: 79.3, previsao_termino: "2025-10-09" },
  { id: "17", nome: "Centro de Convivência do Idoso",              numero_contrato: "CT-2024-0176", secretaria: "Sec. Mun. de Educação",       bairro: "Nova Macaé",             status: "cancelada",    execucao_percentual: 8,  valor_contratado: 3_750_000,  prob_atraso: 0.49, ieop_score: 28.7, previsao_termino: "2026-08-15" },
  { id: "18", nome: "Iluminação LED da Av. Elias Agostinho",       numero_contrato: "CT-2023-0599", secretaria: "Sec. Mun. de Infraestrutura", bairro: "Imbetiba",               status: "em_andamento", execucao_percentual: 71, valor_contratado: 4_600_000,  prob_atraso: 0.38, ieop_score: 68.4, previsao_termino: "2026-05-12" },
];
